### ISSUE TITLE
notcurses-info emoji line leaps into the abyss on macos

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2315]
completely repeatable:

```c
==46263==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0001092ec154 at pc 0x0001092de1d0 bp 0x7ffee6929c10 sp 0x7ffee6929c08
READ of size 1 at 0x0001092ec154 thread T0
    #0 0x1092de1cf in main main.c:499
    #1 0x7fff2046df3c in start+0x0 (libdyld.dylib:x86_64+0x15f3c)

0x0001092ec154 is located 44 bytes to the left of global variable '<string literal>' defined in '/Users/dank/src/notcurses/src/info/main.c:144:21' (0x1092ec180) of size 21
  '<string literal>' is ascii string 'EMOJI NOW (%ld): %s
'
0x0001092ec154 is located 0 bytes to the right of global variable 'emoji' defined in '/Users/dank/src/notcurses/src/info/main.c:107:21' (0x1092ec0a0) of size 180
SUMMARY: AddressSanitizer: global-buffer-overflow main.c:499 in main
Shadow bytes around the buggy address:
  0x10002125d7d0: f9 f9 f9 f9 00 00 00 00 07 f9 f9 f9 f9 f9 f9 f9
  0x10002125d7e0: 00 01 f9 f9 f9 f9 f9 f9 00 00 00 00 00 04 f9 f9
  0x10002125d7f0: f9 f9 f9 f9 00 05 f9 f9 f9 f9 f9 f9 00 05 f9 =46263==ABORTING
Abort trap: 6
[cobra-la](134) $
```

what's up with all this "-1 bytes"?

```
TWAS 4 bytes (total: 99)
EMOJI NOW (103): 🦑🇦🇶👩‍🔬🪤🚱✊🏿🔬🧬🏴‍☠️🤽🏼‍♀️
UTF8: 2 cols, 4 bytes
'TWAS 4 bytes (total: 103)
EMOJI NOW (107): 🇦🇶👩‍🔬🪤🚱✊🏿🔬🧬🏴‍☠️🤽🏼‍♀️
UTF8: 2 cols, 4 bytes
'TWAS 4 bytes (total: 107)
EMOJI NOW (111): 🇶👩‍🔬🪤🚱✊🏿🔬🧬🏴‍☠️🤽🏼‍♀️
UTF8: 2 cols, 4 bytes
'TWAS 4 bytes (total: 111)
EMOJI NOW (115): 👩‍🔬🪤🚱✊🏿🔬🧬🏴‍☠️🤽🏼‍♀️
UTF8: 2 cols, -1 bytes
'TWAS 4 bytes (total: 115)
EMOJI NOW (119): ‍🔬🪤🚱✊🏿🔬🧬🏴‍☠️🤽🏼‍♀️
UTF8: 0 cols, -1 bytes
'TWAS 4 bytes (total: 119)
EMOJI NOW (123): 🪤🚱✊🏿🔬🧬🏴‍☠️🤽🏼‍♀️
UTF8: 0 cols, -1 bytes
'TWAS 4 bytes (total: 123)
EMOJI NOW (127): 🚱✊🏿🔬🧬🏴‍☠️🤽🏼‍♀️
UTF8: 0 cols, -1 bytes
'TWAS 4 bytes (total: 127)
EMOJI NOW (131): ✊🏿🔬🧬🏴‍☠️🤽🏼‍♀️
UTF8: 0 cols, -1 bytes
'TWAS 4 bytes (total: 131)
EMOJI NOW (135): 🏿🔬🧬🏴‍☠️🤽🏼‍♀️
UTF8: 0 cols, -1 bytes
'TWAS 4 bytes (total: 135)
EMOJI NOW (139): 🔬🧬🏴‍☠️🤽🏼‍♀️
UTF8: 0 cols, -1 bytes
'TWAS 4 bytes (total: 139)
EMOJI NOW (143): 🧬🏴‍☠️🤽🏼‍♀️
UTF8: 0 cols, -1 bytes
'TWAS 4 bytes (total: 143)
EMOJI NOW (147): 🏴‍☠️🤽🏼‍♀️
UTF8: 0 cols, -1 bytes
'TWAS 4 bytes (total: 147)
EMOJI NOW (151): ‍☠️🤽🏼‍♀️
UTF8: 0 cols, -1 bytes
'TWAS 4 bytes (total: 151)
EMOJI NOW (155): ☠️🤽🏼‍♀️
UTF8: 0 cols, -1 bytes
'TWAS 4 bytes (total: 155)
EMOJI NOW (159): ️🤽🏼‍♀️
UTF8: 1 cols, 3 bytes
'TWAS 3 bytes (total: 159)
EMOJI NOW (162): 🤽🏼‍♀️
UTF8: 3 cols, -1 bytes
'TWAS 3 bytes (total: 162)
EMOJI NOW (165): 🏼‍♀️
UTF8: 0 cols, -1 bytes
'TWAS 3 bytes (total: 165)
EMOJI NOW (168): ‍♀️
UTF8: 0 cols, -1 bytes
'TWAS 3 bytes (total: 168)
EMOJI NOW (171): ♀️
UTF8: 0 cols, -1 bytes
'TWAS 3 bytes (total: 171)
EMOJI NOW (174): ️
UTF8: 0 cols, -1 bytes
'TWAS 3 bytes (total: 174)
EMOJI NOW (177): 
UTF8: 0 cols, -1 bytes
'TWAS 3 bytes (total: 177)
==============================
```

**Comment by dankamongmen** [comment]
looks like the first failure is 👩‍🔬?

U+1F469 WOMAN
UTF-8: f0 9f 91 a9 UTF-16BE: d83ddc69 Decimal: &#128105; Octal: \0372151
👩
Category: So (Symbol, Other); East Asian width: W (wide)
Unicode block: 1F300..1F5FF; Miscellaneous Symbols and Pictographs
Bidi: ON (Other Neutrals)


U+200D ZERO WIDTH JOINER
UTF-8: e2 80 8d UTF-16BE: 200d Decimal: &#8205; Octal: \020015

Category: Cf (Other, Format); East Asian width: N (neutral)
Unicode block: 2000..206F; General Punctuation
Bidi: BN (Boundary Neutral)


U+1F52C MICROSCOPE
UTF-8: f0 9f 94 ac UTF-16BE: d83ddd2c Decimal: &#128300; Octal: \0372454
🔬
Category: So (Symbol, Other); East Asian width: W (wide)
Unicode block: 1F300..1F5FF; Miscellaneous Symbols and Pictographs
Bidi: ON (Other Neutrals)

ought be 11 bytes, 2 columns

**Comment by dankamongmen** [comment]
0x200d ZWJ comes in as -1 columns:

EMOJI NOW (115): ð<9f><91>©â<80><8d>ð<9f><94>¬ð<9f>ª¤ð<9f><9a>±â<9c><8a>ð<9f><8f>¿ð<9f><94>¬ð<9f>§¬ð<9f><8f>´â<80><8d>â<98> ï¸<8f>ð<
W: 0x0001f469 cols: 2                                                                                                               
W: 0x0000200d cols: -1                                                                                                              
UTF8: 2 cols, -1 bytes                                                                                                              
'TWAS 4 bytes (total: 115)

**Comment by dankamongmen** [comment]
ZWJs and variation selectors oughtn't count as columns. fixed up application. no longer get the ASAN error, and the emoji output is noticeably improved. before:

![2021-11-02-111129_1585x1057_scrot](https://user-images.githubusercontent.com/143473/139874885-527dd253-1ae6-49e4-b381-be8de5b1d795.png)

after:

![2021-11-02-111134_1585x1057_scrot](https://user-images.githubusercontent.com/143473/139874914-2e391c55-3562-4a17-893b-f497ad9ee930.png)
