### ISSUE TITLE
notcurses-pydemo throws "no 'stylemask'" exception

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#942]
the despised python, augh

```
[schwarzgerat](0) $ ./notcurses-pydemo 
Term: 74x80 vte-256color (VTE with xterm 256-colors)

 notcurses 1.6.17 by nick black et al
  74 rows 80 cols (92.50KiB) 16B cells 256 colors (direct)
  compiled with gcc-10.2.0
  terminfo from ncurses 6.2.20200212
  avformat 58.48.100 avutil 56.55.100 swscale 5.8.100
Traceback (most recent call last):
  File "./notcurses-pydemo", line 31, in <module>
    demo()
  File "./notcurses-pydemo", line 8, in demo
    c = notcurses.Cell(nc.stdplane(), ord(' '))
  File "/usr/local/lib/python3.8/dist-packages/notcurses/notcurses.py", line 35, in __init__
    self.c.stylemask = 0
AttributeError: cdata 'struct cell *' has no field 'stylemask'
[schwarzgerat](1) $
```

**Comment by dankamongmen** [comment]
heap-allocated cffi objects are zero-initialized, so we can just drop the offending line entirely.

**Comment by dankamongmen** [comment]
`notcurses-pydemo` works once more.
